// Daftar seluruh universitas di Indonesia
// Sumber: Pangkalan Data Pendidikan Tinggi (PDDikti) Kemdikbud
// Karena terlalu banyak (>4.000 PT), disediakan search/combobox dengan manual input fallback

export const MAJOR_UNIVERSITIES: string[] = [
  // PTN Terkemuka
  'Universitas Indonesia (UI)',
  'Institut Teknologi Bandung (ITB)',
  'Universitas Gadjah Mada (UGM)',
  'Institut Pertanian Bogor (IPB)',
  'Universitas Airlangga (UNAIR)',
  'Institut Teknologi Sepuluh Nopember (ITS)',
  'Universitas Diponegoro (UNDIP)',
  'Universitas Padjadjaran (UNPAD)',
  'Universitas Brawijaya (UB)',
  'Universitas Hasanuddin (UNHAS)',
  'Universitas Sebelas Maret (UNS)',
  'Universitas Pendidikan Indonesia (UPI)',
  'Universitas Negeri Yogyakarta (UNY)',
  'Universitas Negeri Semarang (UNNES)',
  'Universitas Negeri Surabaya (UNESA)',
  'Universitas Negeri Malang (UM)',
  'Universitas Syiah Kuala (USK)',
  'Universitas Sumatera Utara (USU)',
  'Universitas Andalas (UNAND)',
  'Universitas Riau (UNRI)',
  'Universitas Lampung (UNILA)',
  'Universitas Sriwijaya (UNSRI)',
  'Universitas Bengkulu (UNIB)',
  'Universitas Jambi (UNJA)',
  'Universitas Tanjungpura (UNTAN)',
  'Universitas Mulawarman (UNMUL)',
  'Universitas Lambung Mangkurat (ULM)',
  'Universitas Sam Ratulangi (UNSRAT)',
  'Universitas Tadulako (UNTAD)',
  'Universitas Pattimura (UNPATTI)',
  'Universitas Cenderawasih (UNCEN)',
  'Universitas Nusa Cendana (UNDANA)',
  'Universitas Mataram (UNRAM)',
  'Universitas Haluoleo (UHO)',
  'Universitas Khairun (UNKHAIR)',
  'Universitas Papua (UNIPA)',
  'Universitas Palangka Raya (UPR)',

  // PTN Berbadan Hukum / PTN BH
  'Universitas Bina Nusantara (BINUS)',
  'Telkom University',
  'Universitas Mercu Buana',

  // Swasta Terkemuka - Jabodetabek
  'Universitas Pelita Harapan (UPH)',
  'Universitas Trisakti',
  'Universitas Tarumanagara',
  'Universitas Atmajaya Jakarta',
  'Universitas Esa Unggul',
  'Universitas Pancasila',
  'Universitas Nasional',
  'Universitas Gunadarma',
  'Universitas Islam Negeri Syarif Hidayatullah (UIN Jakarta)',
  'STIE Trisakti',
  'Universitas Kristen Indonesia (UKI)',
  'President University',
  'Universitas Al-Azhar Indonesia',
  'Universitas Paramadina',
  'STMIK AMIK Bandung',
  'Sekolah Tinggi Ilmu Ekonomi Indonesia (STEI)',
  'London School of Public Relations Jakarta',

  // Swasta Terkemuka - Jawa Barat
  'Universitas Kristen Maranatha',
  'Universitas Pasundan',
  'Universitas Islam Bandung (UNISBA)',
  'Universitas Komputer Indonesia (UNIKOM)',
  'Universitas Widyatama',
  'Universitas Langlangbuana',
  'Universitas Islam Nusantara (UNINUS)',
  'Universitas Sangga Buana',
  'Universitas Djuanda',
  'Universitas Muhammadiyah Bandung',

  // Swasta Terkemuka - Jawa Tengah & DIY
  'Universitas Muhammadiyah Yogyakarta (UMY)',
  'Universitas Islam Indonesia (UII)',
  'Universitas Atmajaya Yogyakarta (UAJY)',
  'Universitas Sanata Dharma',
  'Universitas Muhammadiyah Surakarta (UMS)',
  'Universitas Dian Nuswantoro (UDINUS)',
  'Universitas Islam Sultan Agung (UNISSULA)',
  'Universitas Stikubank',
  'STMIK AMIKOM Yogyakarta',
  'Universitas Kristen Satya Wacana (UKSW)',
  'Universitas Muhammadiyah Magelang',
  'Universitas Tidar',

  // Swasta Terkemuka - Jawa Timur
  'Universitas Muhammadiyah Malang (UMM)',
  'Universitas Surabaya (UBAYA)',
  'Universitas Kristen Petra',
  'Universitas Widya Mandala Surabaya (UWMS)',
  'STIE Perbanas Surabaya',
  'Universitas Ciputra Surabaya',
  'Universitas Narotama',
  'Universitas Muhammadiyah Sidoarjo (UMSIDA)',
  'Universitas Islam Malang (UNISMA)',
  'Universitas Jember (UNEJ)',

  // Swasta Terkemuka - Bali & NTB
  'Universitas Udayana (UNUD)',
  'Universitas Warmadewa',
  'Universitas Mahasaraswati Denpasar',
  'Institut Teknologi dan Bisnis STIKOM Bali',

  // Swasta Terkemuka - Sumatera
  'Universitas Islam Sumatera Utara (UISU)',
  'Universitas Muhammadiyah Sumatera Utara (UMSU)',
  'Universitas Potensi Utama',
  'Universitas Prima Indonesia',
  'Universitas Muslim Nusantara Al Washliyah',
  'Universitas Bung Hatta',
  'Universitas Muhammadiyah Sumatera Barat',
  'Universitas Islam Riau (UIR)',
  'Universitas Lancang Kuning',
  'Universitas Muhammadiyah Palembang',
  'Universitas Bina Darma Palembang',
  'Institut Informatika dan Bisnis Darmajaya',

  // Swasta Terkemuka - Kalimantan
  'Universitas Muhammadiyah Kalimantan Timur',
  'Sekolah Tinggi Ilmu Ekonomi Samarinda',
  'Universitas Muhammadiyah Pontianak',

  // Swasta Terkemuka - Sulawesi
  'Universitas Muslim Indonesia (UMI)',
  'Universitas 45 Makassar',
  'Universitas Muhammadiyah Makassar',
  'Universitas Islam Makassar',
  'Universitas Kristen Indonesia Tomohon (UKIT)',

  // Sekolah Tinggi, Politeknik, dll
  'Politeknik Negeri Bandung (POLBAN)',
  'Politeknik Negeri Jakarta',
  'Politeknik Negeri Semarang',
  'Politeknik Negeri Surabaya',
  'Politeknik Negeri Malang',
  'Politeknik Elektronika Negeri Surabaya (PENS)',
  'Politeknik Negeri Media Kreatif (POLIMEDIA)',
  'Politeknik Negeri Bali',

  // UIN / IAIN / STAIN
  'Universitas Islam Negeri Maulana Malik Ibrahim Malang (UIN Malang)',
  'Universitas Islam Negeri Sunan Ampel Surabaya (UIN Surabaya)',
  'Universitas Islam Negeri Walisongo Semarang (UIN Walisongo)',
  'Universitas Islam Negeri Sunan Kalijaga Yogyakarta (UIN Yogya)',
  'Universitas Islam Negeri Alauddin Makassar (UIN Makassar)',
  'Universitas Islam Negeri Raden Fatah Palembang (UIN Palembang)',
  'Universitas Islam Negeri Sumatera Utara (UIN Sumut)',
  'Universitas Islam Negeri Ar-Raniry Banda Aceh',
  'Institut Agama Islam Negeri (IAIN) Salatiga',
  'Institut Agama Islam Negeri (IAIN) Pontianak',
]

export const PROVINCES: string[] = [
  'Aceh',
  'Sumatera Utara',
  'Sumatera Barat',
  'Riau',
  'Kepulauan Riau',
  'Jambi',
  'Sumatera Selatan',
  'Bangka Belitung',
  'Bengkulu',
  'Lampung',
  'DKI Jakarta',
  'Jawa Barat',
  'Jawa Tengah',
  'DI Yogyakarta',
  'Jawa Timur',
  'Banten',
  'Bali',
  'Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'Kalimantan Barat',
  'Kalimantan Tengah',
  'Kalimantan Selatan',
  'Kalimantan Timur',
  'Kalimantan Utara',
  'Sulawesi Utara',
  'Sulawesi Tengah',
  'Sulawesi Selatan',
  'Sulawesi Tenggara',
  'Gorontalo',
  'Sulawesi Barat',
  'Maluku',
  'Maluku Utara',
  'Papua Barat',
  'Papua',
  'Papua Selatan',
  'Papua Tengah',
  'Papua Pegunungan',
]

export const MAJORS: string[] = [
  // Teknik
  'Teknik Informatika',
  'Teknik Komputer',
  'Sistem Informasi',
  'Teknologi Informasi',
  'Ilmu Komputer',
  'Teknik Mesin',
  'Teknik Elektro',
  'Teknik Sipil',
  'Teknik Industri',
  'Teknik Kimia',
  'Teknik Lingkungan',
  'Teknik Pertambangan',
  'Teknik Perminyakan',
  'Teknik Metalurgi',
  'Teknik Biomedis',
  'Teknik Penerbangan',
  'Teknik Nuklir',
  'Teknik Material',
  'Teknik Geodesi',
  'Teknik Arsitektur',
  'Teknik Perkapalan',
  'Teknik Kelautan',
  'Teknik Perikanan',

  // Sains & MIPA
  'Matematika',
  'Fisika',
  'Kimia',
  'Biologi',
  'Statistika',
  'Ilmu Aktuaria',
  'Astronomi',
  'Geofisika',
  'Geologi',
  'Meteorologi',
  'Oseanografi',

  // Bisnis & Ekonomi
  'Manajemen',
  'Manajemen Bisnis',
  'Akuntansi',
  'Ekonomi',
  'Ekonomi Islam',
  'Keuangan',
  'Perbankan',
  'Bisnis Internasional',
  'Pemasaran',
  'Kewirausahaan',
  'Administrasi Bisnis',
  'Administrasi Niaga',

  // Hukum & Sosial
  'Hukum',
  'Hukum Internasional',
  'Ilmu Politik',
  'Hubungan Internasional',
  'Ilmu Komunikasi',
  'Sosiologi',
  'Antropologi',
  'Kriminologi',
  'Administrasi Publik',
  'Administrasi Negara',
  'Ilmu Pemerintahan',

  // Kedokteran & Kesehatan
  'Kedokteran',
  'Kedokteran Gigi',
  'Farmasi',
  'Kesehatan Masyarakat',
  'Gizi',
  'Ilmu Keperawatan',
  'Kebidanan',
  'Fisioterapi',
  'Radiologi',
  'Analis Kesehatan',
  'Rekam Medis',

  // Pendidikan
  'Pendidikan Guru SD',
  'Pendidikan Bahasa Indonesia',
  'Pendidikan Bahasa Inggris',
  'Pendidikan Matematika',
  'Pendidikan Fisika',
  'Pendidikan Biologi',
  'Pendidikan Kimia',
  'Pendidikan Teknik Informatika',
  'Bimbingan Konseling',
  'Pendidikan Luar Biasa',
  'Pendidikan Anak Usia Dini (PAUD)',

  // Pertanian & Lingkungan
  'Agroteknologi',
  'Agribisnis',
  'Kehutanan',
  'Ilmu Tanah',
  'Peternakan',
  'Teknologi Pangan',
  'Ilmu Perikanan',
  'Budidaya Perairan',

  // Sastra & Humaniora
  'Sastra Indonesia',
  'Sastra Inggris',
  'Sastra Jepang',
  'Sastra Mandarin',
  'Sastra Arab',
  'Sastra Perancis',
  'Linguistik',
  'Filsafat',
  'Sejarah',

  // Seni & Desain
  'Desain Komunikasi Visual (DKV)',
  'Desain Produk',
  'Desain Interior',
  'Arsitektur Lanskap',
  'Seni Rupa',
  'Seni Murni',
  'Seni Pertunjukan',
  'Musik',
  'Film & Televisi',
  'Fotografi',
  'Animasi',

  // Psikologi & Lainnya
  'Psikologi',
  'Ilmu Perpustakaan',
  'Pariwisata',
  'Perhotelan',
  'Ilmu Gizi',
  'Ilmu Olahraga',
]
