// Daftar opsi yang dipakai bersama oleh form onboarding & pengaturan profil.

export const PROVINCE_OPTIONS = [
  'Aceh',
  'Sumatera Utara',
  'Sumatera Barat',
  'Riau',
  'Kepulauan Riau',
  'Jambi',
  'Sumatera Selatan',
  'Bangka Belitung',
  'Bengkulu',
  'Lampung',
  'Banten',
  'DKI Jakarta',
  'Jawa Barat',
  'Jawa Tengah',
  'DI Yogyakarta',
  'Jawa Timur',
  'Bali',
  'Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'Kalimantan Barat',
  'Kalimantan Tengah',
  'Kalimantan Selatan',
  'Kalimantan Timur',
  'Kalimantan Utara',
  'Sulawesi Utara',
  'Gorontalo',
  'Sulawesi Tengah',
  'Sulawesi Barat',
  'Sulawesi Selatan',
  'Sulawesi Tenggara',
  'Maluku',
  'Maluku Utara',
  'Papua',
  'Papua Barat',
  'Papua Barat Daya',
  'Papua Tengah',
  'Papua Pegunungan',
  'Papua Selatan',
  'Lainnya',
]

export const UNIVERSITY_OPTIONS = [
  'Universitas Indonesia',
  'Universitas Gadjah Mada',
  'Institut Teknologi Bandung',
  'Institut Pertanian Bogor',
  'Institut Teknologi Sepuluh Nopember',
  'Universitas Airlangga',
  'Universitas Padjadjaran',
  'Universitas Diponegoro',
  'Universitas Brawijaya',
  'Universitas Sebelas Maret',
  'Universitas Sumatera Utara',
  'Universitas Andalas',
  'Universitas Sriwijaya',
  'Universitas Lampung',
  'Universitas Riau',
  'Universitas Jambi',
  'Universitas Bengkulu',
  'Universitas Syiah Kuala',
  'Universitas Negeri Jakarta',
  'Universitas Pendidikan Indonesia',
  'Universitas Negeri Yogyakarta',
  'Universitas Negeri Semarang',
  'Universitas Negeri Malang',
  'Universitas Negeri Surabaya',
  'Universitas Negeri Padang',
  'Universitas Negeri Medan',
  'Universitas Negeri Makassar',
  'Universitas Udayana',
  'Universitas Mataram',
  'Universitas Nusa Cendana',
  'Universitas Tanjungpura',
  'Universitas Lambung Mangkurat',
  'Universitas Mulawarman',
  'Universitas Palangka Raya',
  'Universitas Hasanuddin',
  'Universitas Sam Ratulangi',
  'Universitas Tadulako',
  'Universitas Halu Oleo',
  'Universitas Pattimura',
  'Universitas Cenderawasih',
  'Universitas Terbuka',
  'Universitas Gunadarma',
  'Universitas Bina Nusantara',
  'Universitas Telkom',
  'Universitas Trisakti',
  'Universitas Tarumanagara',
  'Universitas Atma Jaya Jakarta',
  'Universitas Pelita Harapan',
  'Universitas Mercu Buana',
  'Universitas Esa Unggul',
  'Universitas Muhammadiyah Yogyakarta',
  'Universitas Muhammadiyah Malang',
  'Universitas Ahmad Dahlan',
  'Universitas Islam Indonesia',
  'Universitas Islam Negeri Syarif Hidayatullah Jakarta',
  'Universitas Islam Negeri Sunan Kalijaga Yogyakarta',
  'Universitas Islam Negeri Maulana Malik Ibrahim Malang',
  'Universitas Kristen Satya Wacana',
  'Universitas Kristen Petra',
  'Universitas Katolik Parahyangan',
  'Politeknik Negeri Jakarta',
  'Politeknik Negeri Bandung',
  'Politeknik Elektronika Negeri Surabaya',
  'Politeknik Negeri Malang',
]

export const MAJOR_OPTIONS = [
  'Akuntansi',
  'Arsitektur',
  'Biologi',
  'Bisnis Digital',
  'Desain Komunikasi Visual',
  'Ekonomi Pembangunan',
  'Farmasi',
  'Fisika',
  'Hubungan Internasional',
  'Hukum',
  'Ilmu Administrasi',
  'Ilmu Komunikasi',
  'Ilmu Komputer',
  'Ilmu Politik',
  'Kedokteran',
  'Keperawatan',
  'Kimia',
  'Manajemen',
  'Matematika',
  'Pendidikan',
  'Psikologi',
  'Sastra Inggris',
  'Sistem Informasi',
  'Statistika',
  'Teknik Elektro',
  'Teknik Industri',
  'Teknik Informatika',
  'Teknik Kimia',
  'Teknik Mesin',
  'Teknik Metalurgi',
  'Teknik Sipil',
  'Teknologi Informasi',
  'Lainnya',
]

export const GENDER_OPTIONS = [
  { value: '', label: 'Tidak diisi' },
  { value: 'laki_laki', label: 'Laki-laki' },
  { value: 'perempuan', label: 'Perempuan' },
  { value: 'lainnya', label: 'Lainnya' },
  { value: 'tidak_ingin_menyebutkan', label: 'Tidak ingin menyebutkan' },
]
